nodeLinker: node-modules

npmScopes:
    d-lift:
        npmAuthToken: 6fd99e4c-02e6-4533-b9fc-3b83d48019f6
        npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
    eslint-config-react-app@*:
        dependencies:
            '@typescript-eslint/eslint-plugin': ^2.0.0
            '@typescript-eslint/parser': ^2.0.0
            babel-eslint: ^10.0.0
            eslint: ^6.0.0
            eslint-plugin-flowtype: ^3.0.0
            eslint-plugin-import: ^2.0.0
            eslint-plugin-jsx-a11y: ^6.0.0
            eslint-plugin-react: ^7.0.0
            eslint-plugin-react-hooks: ^2.0.0
            fsevents: 2.1.3
    react-bootstrap-table2-paginator@*:
        dependencies:
            classnames: ^2.2.5
    react-detect-offline@*:
        dependencies:
            prop-types: ^15.7.2
            react: '*'
    sass-loader@*:
        dependencies:
            node-sass: '*'
    sync-monorepo-packages@*:
        dependencies:
            cp-file: ^9.0.0

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
      spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

progressBarStyle: default

yarnPath: .yarn/releases/yarn-3.2.0.cjs
